image: gitpod/workspace-full

tasks:
  - name: Emitter
    init: rm -rf ./.gitpod.lock && yarn install && touch ./.gitpod.lock
    command: node send.js foobar
    openIn: bottom
    openMode: tab-before
  - name: Api
    init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
    command: yarn start:gitpod:api
    openIn: bottom
    openMode: split-right
#   - name: Unit Tests
#     init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
#     command: yarn tdd:unit
#     openIn: right
#     openMode: tab-after
#   - name: E2E Tests
#     init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
#     command: yarn tdd:e2e
#     openIn: right
#     openMode: tab-after
#   - name: Styleguide
#     init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
#     command: yarn start:gitpod:styleguide
#     openIn: bottom
#     openMode: split-right
#   - name: App
#     init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
#     command: yarn start:gitpod:app
#     openIn: bottom
#     openMode: tab-after

# ports:
#   - port: 5432
#     onOpen: ignore
#   - port: 8008
#     onOpen: ignore
#   - port: 8080
#     onOpen: ignore
#   - port: 3000
#     onOpen: ignore
#   - port: 6060
#     onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - mikestead.dotenv@1.0.1:SSXjr5hZcbqSF7nMIhTNnA==
    - wayou.vscode-todo-highlight@1.0.4:8IqxuxCVol2WnScJc5xVzg==
